FROM nvidia/cuda:12.3.0-base-ubuntu22.04
RUN apt-get update && \
    apt-get install -y python3 python3-pip curl git && \
    rm -rf /var/lib/apt/lists/*
RUN pip3 install --upgrade pip
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt fastapi uvicorn
RUN opentelemetry-bootstrap --action=install
WORKDIR /app
COPY ./ /app/
EXPOSE 8080
CMD ["opentelemetry-instrument", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]